- submodules/users/users.css
- submodules/users/users.js
- Clicking on the appropriate header in the smart pbx user list
will sort by that column.
> UI-2945 - Allow user list in smart pbx to be sorted

- i18n/en-US.json
- submodules/users/users.js
- views/users-feature-do_not_disturb.html
Achieved via user features and presence. Relies on [#4553.](https://github.com/2600hz/kazoo/pull/4553)
> Add do not disturb user feature

- submodules/strategy/strategy.js
to accep the number to forward to.
This is a port of #51 to 4.2
> Make call forward activate feature code a pattern

- i18n/en-US.json
- submodules/users/users.js
Also some small improvements to user creation, to not to leave the user half-way created if charges are not accepted.
> UI-3274: Clean up HTTP 402 error guards on callApi error callbacks

- submodules/strategy/strategy.js
4.3 -> https://github.com/2600hz/monster-ui-voip/pull/165
> MSPB-15: Revert "MSPB-14: Use correct module name for feature code check (#162)"

- submodules/callLogs/callLogs.js
Include timestamp in SmartPBX email reports
> MSPB-61: Include timestamp in SmartPBX email reports

- submodules/callLogs/callLogs.js
Include timestamp in SmartPBX email reports
> [4.3] MSPB-61: Include timestamp in SmartPBX email reports

- submodules/myOffice/myOffice.js
Feature sections where not being shown in the Caller ID dialog because [the available features path changed in the number document](https://github.com/2600hz/monster-ui/pull/589).
4.3 -> #180
> MSPB-67: Show feature sections at Caller ID dialog

- i18n/en-US.json
- submodules/strategyHours/_strategyHours.scss
- submodules/strategyHours/strategyHours.js
- submodules/strategyHours/views/layout.html
This feature relies on the office hours refactor (breaking change), which is still under QA.
Please test this under a dev account!
> MSPB-93: Add office hours export as CSV

- submodules/strategyHours/strategyHours.js
> [5.0] MSPB-159: Normalize temporal rules time window values

- submodules/strategy/strategy.js
> [4.3] MSPB-160: Remove default feature codes config enforcer

- submodules/strategyHours/strategyHours.js
Relies on:
- https://github.com/2600hz/monster-ui/pull/875
> MSPB-157: Move row validation to CSV uploader common control

- i18n/en-US.json
- submodules/groups/groups.js
- submodules/groups/views/feature-call_recording.html
> MSPB-176: Add SFTP as supported protocol for recording destionation

- submodules/users/users.js
> [5.0] MSPB-181: Fix user call recording settings rendered improperly

- submodules/users/users.js
5.0 -> https://github.com/2600hz/monster-ui-voip/pull/375
> MSPB-181: Fix check to determine whether call recording is set

- i18n/en-US.json
- submodules/myOffice/myOffice.js
- submodules/myOffice/partials/_callerIdPopup.scss
- submodules/myOffice/views/callerIdPopup.html
- submodules/users/users.js
- submodules/users/users.scss
- submodules/users/views/feature-caller_id.html
Reverts 2600hz/monster-ui-voip#388
> Revert "PROD-199: Implement CID number selector"

- i18n/en-US.json
- submodules/devices/devices.js
- submodules/devices/devices.scss
- submodules/devices/views/devices-teammate.html
- submodules/devices/views/layout.html
- submodules/devices/views/row.html
- submodules/myOffice/myOffice.js
- submodules/users/users.js
- submodules/users/views/devices.html
- submodules/users/views/row.html
5.0 PR: https://github.com/2600hz/monster-ui-voip/pull/406
Ticket: https://2600hz-commercial.atlassian.net/browse/MSPB-215
Screenshots:
> MSPB-215: add support for teammate device

- i18n/en-US.json
- submodules/devices/devices.js
- submodules/devices/devices.scss
- submodules/devices/views/devices-teammate.html
- submodules/devices/views/layout.html
- submodules/devices/views/row.html
- submodules/myOffice/myOffice.js
- submodules/users/users.js
- submodules/users/views/devices.html
- submodules/users/views/row.html
> [5.0] MSPB-215: Add support for teammate device

- submodules/devices/devices.js
5.0 PR: https://github.com/2600hz/monster-ui-voip/pull/409
5.1 PR: https://github.com/2600hz/monster-ui-voip/pull/410
> mspb-215: fix teammate device payload

- app.js
- move provisioner check to render methods
- remove load and initApp methods
> MSPB-249: fix Add Device section on user creation

- app.js
- move provisioner check to render methods
- remove load and initApp methods
master pr: https://github.com/2600hz/monster-ui-voip/pull/420
> [5.1] MSPB-249: fix Add Device section on user creation

- submodules/devices/devices.js
- submodules/users/users.js
master pr: https://github.com/2600hz/monster-ui-voip/pull/426
> [5.1] MSTR-226: split call_failover in separate object

- submodules/users/users.js
master pr: https://github.com/2600hz/monster-ui-voip/pull/434
ticket: https://2600hz-commercial.atlassian.net/browse/MSPB-254
> [5.1] MSPB-254: fix usersFormatCallForwardData

- submodules/users/users.scss
- submodules/users/views/layout.html
- submodules/vmboxes/views/layout.html
- submodules/vmboxes/vmboxes.css
- Make users header style generic
- Render user creation action conditionally
> MSPB-257,MSPB-285: Render user creation action conditonally

- views/app.html
- Render numbers tab based on feature set
- Render groups tab based on feature set
- Render devices tab based on feature set
> MSPB-259,MSPB-262,MSPB-265: Render numbers/devices/groups tab based on feature set

- app.js
Better logic for https://github.com/2600hz/monster-ui-voip/pull/470
> MSPB-315: External event based routing based on feature set

- app.js
- submodules/groups/groups.js
- submodules/myOffice/myOffice.js
- submodules/strategy/strategy.js
- submodules/users/users.js
Added logic for disabling new user walkthrough in SmartPBX for sections Dashboard/myOffice, Users, Groups and Main Number/strategy.
> MSPB-319: Added ability to disable walkthrough as per configuration

- submodules/strategyHolidays/strategyHolidays.js
Import fix for library update to version 3.19.0
> MSTR-245: Import fix for date-holidays update

- submodules/strategyHolidays/strategyHolidays.js
Import fix for library update to version 3.19.0
> [5.2 ]MSTR-245: Import fix for date-holidays update

- submodules/devices/devices.js
- submodules/users/users.js
> [5.3] Show meta device as active

- submodules/strategy/strategy.js
Implement timestamp versioning for TTS updates in SmartPBX to prevent duplicates. Now, each TTS update appends new `Date().getTime()` for uniqueness.
> MSPB-344: Fix Duplicate TTS Generation in SmartPBX with Timestamp Versioning

- submodules/strategy/strategy.js
Implement timestamp versioning for TTS updates in SmartPBX to prevent duplicates. Now, each TTS update appends new `Date().getTime()` for uniqueness.
> [5.1] MSPB-344: Fix Duplicate TTS Generation in SmartPBX with Timestamp Versioning

- submodules/strategy/strategy.js
Implement timestamp versioning for TTS updates in SmartPBX to prevent duplicates. Now, each TTS update appends new `Date().getTime()` for uniqueness.
> [5.3] MSPB-344: Fix Duplicate TTS Generation in SmartPBX with Timestamp Versioning

- app.js
- submodules/callLogs/callLogs.js
Moved from flag/bindEvents based cross-site message routing to event subscribe.
> MSPB-315: Updated cross-site message based routing

- i18n/en-US.json
- submodules/strategy/strategy.js
- submodules/users/users.js
- submodules/users/users.scss
- submodules/users/views/newExtension.html
> MSPB-366: Validate if extesion already exist on users management section

- submodules/users/users.js
This reverts commit f6d8a9ba57eab78c3aaf2b1fe1c7b2a8ddc2c93a.
> Revert "[5.4] MCAS-6: Validate special character not allowed (#561)"

- i18n/en-US.json
- submodules/myOffice/myOffice.js
- submodules/myOffice/views/callerIdPopup.html
* MSTR-300: Add support to intrado when adding a e911 to a number
* Fix issue where address is not set
> [5.4] MSTR-300: Add support to Intrado when adding a e911 to a number (#535)
