views/devices-sip_device.html

this typo used with toLowerCase causes an exception and prevents the popup dialog to show

fix - typo that prevents display/edit sip device

---

submodules/strategy/strategy.js

Fixes the MainFaxig callflow module name. It should be "faxbox" instead of "faxing".

UI-1840: Correct module name typo in the MainFaxing callflow

---

submodules/devices/devices.js

It was missing the .key class and was only populating feature keys due to hard coded class (.feature_keys)

UI-2562: Fix CSS selector to populate key value

---

submodules/myOffice/myOffice.js

This removes the default pagination limit of the SmartPBX directory grab, which limited the directory user count to 50 or less and also limited the PDF download to only include 50 or less users.

UI-3019: Fix dashboard 50 user count and PDF directory limit

---

i18n/en-US.json
submodules/users/users.js
views/users-feature-caller_id.html

Toggling a new config setting allows choice between two different ways a user can set a user's caller ID. It can either be the standard way (only able to choose numbers assigned to the user, otherwise main number is used) or being able to choose any number belonging to the account.

Toggle user caller id strategy

---

submodules/strategy/strategy.js

Change the Call Forward Activate strategy feature code to be a pattern.
This makes it easier to use native IP phone settings to set call forward number, without having to go through the voice prompt.

Call Forward Activate pattern

---

submodules/devices/devices.css
submodules/devices/devices.js
views/devices-sip_device.html

UI-3053 - This addition allows for reordering of feature keys while editing a device from Smart PBX.  This utilizes JQuery sortable and resaves the data in the specified order when saving.

UI-3053: Added Smart PBX SIP Device feature key drag and drop reordering

---

submodules/groups/groups.js

When creating groups on SmartPBX, the app automatically generates
baseGroup/userGroup callflows depending on which users are part of the
group. On the other end, the Callflows app only creates a group without
any callflow.
Since SmartPBX is listing all groups, an error was raised when trying to
view the details of group created through the Callflows app since an
associated callflow does not exist.

UI-3096: Only list groups created with SmartPBX

---

submodules/strategy/strategy.js

As per issue UI-3140, currenly the time of day object for lunch hours contains all weekdays by default. This needs to reflect the days the business is open. On days the business is closed, the lunch hours time of day object should not be valid.

 UI-3140: Lunch hours time of day object will only be valid on days the business is open

---

submodules/users/users.js
submodules/users/views/changePresenceIDPopup.html

To prevent a user from saving the changes without selecting any valid option, thus setting 'null' as a value for the user's `presence_id`.

UI-3286: Set default option on select main extension pop-up

---

submodules/users/users.js

Had to merge #132 as it was fixing a somewhat critical bug (the fact that voicemail box indicators do not appear properly was factored in).
As you can see, the property to check against is now `skipped_modules` so I just wanted to see if you could think of any side effects following this change since you are the feature owner.

UI-3328: Reverse module presence check to compare against skipped_modules

---

submodules/users/users.js

The "Restart" button is grayed out when accessed via the “User” page, but is available via “Device” page within the 2600/Kazoo stack.
Steps to Reproduce:
- Log in
- Navigate to the Smart PBX app
- Navigate to the Users panel
- Chose a user with a working desktop phone
- Click on the desktop phone icon
- Click on the name of the device
- Chose the Advanced option
- Chose Miscellaneous 
Actual Results: The Restart phone button is grayed out
Expected Results: The Restart phone button should not be grayed out. 
This pull request fixes this issue, allowing devices to be restarted from the User page.

MSPB-4: Allow devices to be restarted from user page

---

submodules/myOffice/myOffice.js

The goal of this PR was to untangle the logic used to prepare and format data entities for the rendering of the "Dashboard" tab.
The main concern of this refactoring was to keep a similar output, as updating templates was out-of-scope as well as not introducing any regressions. A secondary concern was to preserve the datasets color scheme order so the end-users do not experience any visual change.
To review this PR, I'd recommend going through each commit individually as they are fairly self contained, and here is an (hopefully) exhaustive list explaining the more obscure parts of the code implemented to meet those concerns:
1. [For number statuses](https://github.com/2600hz/monster-ui-voip/pull/166/commits/49d500a573bfc0f14b17648b6578f52213ef4c80#diff-436b0db36fd89dedc678b61972cb5d35R628) …

MSPB-8: Refactor dashboard data formatter

---

submodules/devices/devices.js

Filter function types by a brand flag in `config.js`:  `provisioner.brands.<brand>.functions.<array>`
Example:
```
{
provisioner: {
brands: {
avaya: {
functions: [
'presence',
'parking',
'speed_dial'
]       
}
}
}
}
```

MSPB-102: Allow key function types filtering by brand for device edit form

---

submodules/devices/devices.js

Filter function types by a brand flag in `config.js`:  `provisioner.brands.<brand>.functions.<array>`
Example:
```
{
provisioner: {
brands: {
avaya: {
functions: [
'presence',
'parking',
'speed_dial'
]       
}
}
}
}
```

[4.3] MSPB-102: Allow key function types filtering by brand for device edit form

---

submodules/groups/groups.js

'voicemails' not valid schema. Corrected typo for valid 'callflows.voicemail' schema

'voicemails' not valid schema

---

app.js
style/app.css
submodules/groups/groups.css
submodules/groups/groups.js
submodules/users/users.js
submodules/users/users.scss

The main goal of this PR is to takle the following use case:
-> navigate to Smart PBX app
-> click "Users" tab
-> click any section of user row to open the overlay
-> switch to another app with shortcut or by updating route
-> the overlay would still be present since it is appeneded to the body directly

Move users/groups overlay into app container

---

i18n/de-DE.json
i18n/en-US.json
submodules/devices/devices.js
submodules/devices/devices.scss
submodules/devices/views/devices-sip_device.html

To set default line keys by a brand you need to use a flag in config.js: provisioner.brands.<brand>.lineKeys.<array>
Example: 
```javascript
provisioner: {
brands: {
avaya: {
lineKeys: [1, 2]
}
}
}
```

MSPB-108: Avaya customizations

---

app.js
submodules/devices/devices.js
submodules/users/users.js

The goal of this PR is to update the callflow related to a mobile device when such a device gets un\assigned under the "Devices" module as it currently only updates the device entity.
Since the logic to achieve that callflow update already exists for the "Users" module, a lot of refactoring took place to [extract ](https://github.com/2600hz/monster-ui-voip/pull/254/files#diff-0364f57fbff2fabbe941ed20c328ef1aR234)it into its own method so it can be reused [in](https://github.com/2600hz/monster-ui-voip/pull/254/files#diff-9d41170cfbf87d93b3bc4cb8b757ef0cR1471) different [places](https://github.com/2600hz/monster-ui-voip/pull/254/files#diff-3f48311df930d8c96c10dc025d5a2417R4933).
Another improvement made in this PR, which is a direct consequence of extracting common logic into reusable …

MSPB-131: Update linked callflow on mobile device un\assignment

---

submodules/devices/devices.js
submodules/myOffice/myOffice.js
submodules/users/users.js

The goal of this PR is to remove the need for the UI to keep a track of registrable devices. Although this operation could have been abstracted into a util, the fact is that when kazoo introduces a new device type, we have manually to update our list.
Thanks to the new `with_status=true` flag on `/devices`, we can now request device statuses in the same payload to determine both registrability and registered states. That information is exposed by the `registrable=true|false` and `registered=true|false` props respectively.
Requires https://github.com/2600hz/kazoo-crossbar/pull/63
Related PRs:
https://github.com/2600hz/monster-ui-callflows/pull/140
https://github.com/2600hz/monster-ui-callqueues/pull/137
https://github.com/2600hz/monster-ui-callqueues-pro/pull/356 …

MSPB-138: Solve device statuses from listing endpoint

---

app.js

The outbound privacy options seem to be accidentally removed by #336

MSPB-180: Re-add outbound privacy options to appFlags

---

submodules/strategy/strategy.js

...considerations
1. If the account already a emergency cid, it doesn't do anything
2. If there is no emergency cid in the account, we check if the given number already have the e911 setup, if true, is added as emergency cid.
[5.0](https://github.com/2600hz/monster-ui-voip/pull/390)

MSPB-167: Add given main number as e911 if it's valid

---

submodules/strategy/strategy.js

...considerations
1. If the account already a emergency cid, it doesn't do anything
2. If there is no emergency cid in the account, we check if the given number already have the e911 setup, if true, is added as emergency cid.

[5.0] MSPB-167: Add given main number as e911 if it's valid

---

submodules/users/users.js

Duplicate call forwarding settings into a failover object (account, user, device) and remove ‘failover’ as a call forward option.
The intend is to allow users to be able to change their call forwarding settings without impacting the failover settings and have failover set independently from forward.

PROD-169: split failover from forward

---

submodules/users/users.js

Duplicate call forwarding settings into a fail over object (account, user, device) and remove ‘fail over’ as a call forward option.
The intend is to allow users to be able to change their call forwarding settings without impacting the fail over settings and have fail over set independently from forward.

[5.1] PROD-169: split failover from forward

---

submodules/strategy/strategy.js

When loading the Main Number page, delete any callflows that have the same feature code name as the ones automatically created by the Smart PBX ap, but that have been created outside of this app.

MSPB-323: Delete feature codes with same names as SPBX ones

---

submodules/strategy/strategy.js

When loading the Main Number page, delete any callflows that have the same feature code name as the ones automatically created by the Smart PBX ap, but that have been created outside of this app.

[5.1] MSPB-323: Delete feature codes with same names as SPBX ones

---

submodules/devices/devices.js
submodules/users/users.js

Show meta device as active

---

submodules/devices/devices.js

This removes the section `call_failover` when creating a new Smartphone device, this is due to a change in the API that split call_forward.number from call_failover.number: [kazoo-crossbar #179](https://github.com/2600hz/kazoo-crossbar/pull/179).
As a result it was decided to remove the `call_failover` section of the payload ([accounts.md#call_failover](https://github.com/2600hz/kazoo-crossbar/blob/master/doc/accounts.md#call_failover)) and keep it only available through the API.

MSPB-341: Adding a Smartphone Device in SPBX Errors out

---

submodules/devices/devices.js

This removes the section call_failover when creating a new Smartphone device, this is due to a change in the API that split call_forward.number from call_failover.number: https://github.com/2600hz/kazoo-crossbar/pull/179.
As a result it was decided to remove the call_failover section of the payload ([accounts.md#call_failover](https://github.com/2600hz/kazoo-crossbar/blob/master/doc/accounts.md#call_failover)) and keep it only available through the API.

[5.1] MSPB-341: Adding a Smartphone Device in SPBX Errors out

---

submodules/devices/devices.js

This removes the section call_failover when creating a new Smartphone device, this is due to a change in the API that split call_forward.number from call_failover.number: https://github.com/2600hz/kazoo-crossbar/pull/179.
As a result it was decided to remove the call_failover section of the payload ([accounts.md#call_failover](https://github.com/2600hz/kazoo-crossbar/blob/master/doc/accounts.md#call_failover)) and keep it only available through the API.

[5.3] MSPB-341: Adding a Smartphone Device in SPBX Errors out

---

submodules/strategy/strategy.js

Implement timestamp versioning for TTS updates in SmartPBX to prevent duplicates. Now, each TTS update appends new `Date().getTime()` for uniqueness.

[5.2] MSPB-344: Fix Duplicate TTS Generation in SmartPBX with Timestamp Versioning

---

app.js
submodules/callLogs/callLogs.js

Moved from flag/bindEvents based cross-site message routing to event subscribe.

[5.3] MSPB-315: Updated cross-site message based routing

---

app.js

If the app assets is loading from external `source_url`, if the app tries to require its sub modules directly it will fail and the app won't load at all.
Changing the module name to its external `source_url` as what Monster UI core was previously doing won't always work in case the sub modules were small enough and optimized away in a single file as `app.js`. This has been observed with `branding` and `call-recording` apps so far.
Instead we can explicitly config the paths for sub module and its external source url for `requirejs` to load it, if it is not already optimized in the `app.js`.
Without this change, because `app.js` is requiring the submodules, this URL will be used instead of external source_url:
```
http://{monster_ui_url}/apps/:appname/submodules/{submodule}/{submodule}.js …
```

[5.3] MSTR-275: do not require sub module, let core handle it

---

submodules/strategy/strategy.js

- Enabling `whitelabel` support for `tts.voice` changes in SmartPBX

MSPB-385: Add `tts.voice` `whitelabel` support

---

submodules/strategy/strategy.js

- Enabling `whitelabel` support for `tts.voice` changes in SmartPBX

[5.4] MSPB-385: Add `tts.voice` `whitelabel` support

---

submodules/strategy/views/menuLine.html

Add `timeout` selection to SmartPBX Main Number incoming call handling to match functionality available in Callflows. Executes configured `timeout` `child` `flow` when no user input is received within timeout period.
**API Change:**
```diff
"children": {
"0": { ... },
"1": { ... },
+ "timeout": { ... }
}
```
References: [Menus API](https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/menus.md)

MSPB-390: add `timeout` option to SmartPBX incoming call handling

---

submodules/strategy/views/menuLine.html

Add `timeout` selection to SmartPBX Main Number incoming call handling to match functionality available in Callflows. Executes configured `timeout` `child` `flow` when no user input is received within timeout period.
**API Change:**
```diff
"children": {
"0": { ... },
"1": { ... },
+ "timeout": { ... }
}
```
References: [Menus API](https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/menus.md)

[5.4] MSPB-390: add `timeout` option to SmartPBX incoming call handling

---

submodules/strategy/views/menuLine.html

Add `timeout` selection to SmartPBX Main Number incoming call handling to match functionality available in Callflows. Executes configured `timeout` `child` `flow` when no user input is received within timeout period.
**API Change:**
```diff
"children": {
"0": { ... },
"1": { ... },
+ "timeout": { ... }
}
```
References: [Menus API](https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/menus.md)

[5.5] MSPB-390: add `timeout` option to SmartPBX incoming call handling
